version: '3'
services:
  app:
    image: lavender5/ethereum_health_checker:latest
    container_name: eth_health
    restart: unless-stopped
    env_file:
      - ".env"
    ports:
      - "53336:53336"
